- name: create and copy the kickstart file of the machine
  template:
    src: "pel7/kickstart.cfg"
    dest: "{{virtualfilespath }}{{ inventory_hostname }}.cfg"
  delegate_to: "{{ hyper }}"

- name: make install script
  template:
    src: "common/install-vm.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: execute install script
  raw: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
  delegate_to: "{{ hyper }}"
  register: createdvm

- name: wait for vm to install
  local_action: pause minutes={{ vmwaittime }}
